export const PREDICTIVE_REFERENCE_APPENDIX = [
    {
        id: "gold-report",
        organization: "Global Initiative for Chronic Obstructive Lung Disease",
        title: "Global Strategy for the Diagnosis, Management, and Prevention of COPD",
        publisher: "GOLD",
        year: "2024",
        url: "https://goldcopd.org/",
        domain: "pulmonology",
        type: "guideline",
    },
    {
        id: "ats-guidance",
        organization: "American Thoracic Society",
        title: "Clinical Practice Guidance and Statements",
        publisher: "ATS",
        year: "2024",
        url: "https://www.thoracic.org/",
        domain: "pulmonology",
        type: "society-guidance",
    },
    {
        id: "ers-guidance",
        organization: "European Respiratory Society",
        title: "ERS Guidelines and Clinical Resources",
        publisher: "ERS",
        year: "2024",
        url: "https://www.ersnet.org/",
        domain: "pulmonology",
        type: "society-guidance",
    },
    {
        id: "aha-guidelines",
        organization: "American Heart Association",
        title: "Clinical Practice Guidelines and Scientific Statements",
        publisher: "AHA",
        year: "2024",
        url: "https://www.heart.org/",
        domain: "cardiology",
        type: "guideline",
    },
    {
        id: "acc-guidelines",
        organization: "American College of Cardiology",
        title: "Guidelines and Expert Consensus Documents",
        publisher: "ACC",
        year: "2024",
        url: "https://www.acc.org/",
        domain: "cardiology",
        type: "guideline",
    },
    {
        id: "nccn-guidelines",
        organization: "National Comprehensive Cancer Network",
        title: "NCCN Clinical Practice Guidelines in Oncology",
        publisher: "NCCN",
        year: "2024",
        url: "https://www.nccn.org/",
        domain: "oncology",
        type: "guideline",
    },
    {
        id: "asco-guidelines",
        organization: "American Society of Clinical Oncology",
        title: "ASCO Guidelines and Standards",
        publisher: "ASCO",
        year: "2024",
        url: "https://www.asco.org/",
        domain: "oncology",
        type: "guideline",
    },
    {
        id: "esmo-guidelines",
        organization: "European Society for Medical Oncology",
        title: "ESMO Clinical Practice Guidelines",
        publisher: "ESMO",
        year: "2024",
        url: "https://www.esmo.org/",
        domain: "oncology",
        type: "guideline",
    },
    {
        id: "aafp-guidance",
        organization: "American Academy of Family Physicians",
        title: "Clinical Recommendations and Practice Guidance",
        publisher: "AAFP",
        year: "2024",
        url: "https://www.aafp.org/",
        domain: "primary_care",
        type: "society-guidance",
    },
    {
        id: "acp-guidance",
        organization: "American College of Physicians",
        title: "Clinical Guidelines and Best Practice Advice",
        publisher: "ACP",
        year: "2024",
        url: "https://www.acponline.org/",
        domain: "primary_care",
        type: "society-guidance",
    },
    {
        id: "pubmed",
        organization: "U.S. National Library of Medicine",
        title: "PubMed Indexed Biomedical Literature",
        publisher: "NLM",
        year: "2024",
        url: "https://pubmed.ncbi.nlm.nih.gov/",
        domain: "cross-domain",
        type: "literature-index",
    },
    {
        id: "fda-safety",
        organization: "U.S. Food and Drug Administration",
        title: "Drug Safety Communications",
        publisher: "FDA",
        year: "2024",
        url: "https://www.fda.gov/drugs/drug-safety-and-availability/drug-safety-communications",
        domain: "cross-domain",
        type: "regulatory-safety",
    },
    {
        id: "nejm",
        organization: "New England Journal of Medicine",
        title: "NEJM Clinical Research and Reviews",
        publisher: "Massachusetts Medical Society",
        year: "2024",
        url: "https://www.nejm.org/",
        domain: "cross-domain",
        type: "peer-reviewed-journal",
    },
    {
        id: "jama",
        organization: "JAMA Network",
        title: "JAMA Original Investigation and Clinical Reviews",
        publisher: "American Medical Association",
        year: "2024",
        url: "https://jamanetwork.com/journals/jama",
        domain: "cross-domain",
        type: "peer-reviewed-journal",
    },
    {
        id: "jacc",
        organization: "Journal of the American College of Cardiology",
        title: "JACC Clinical and Outcomes Research",
        publisher: "Elsevier",
        year: "2024",
        url: "https://www.jacc.org/",
        domain: "cardiology",
        type: "peer-reviewed-journal",
    },
    {
        id: "circulation",
        organization: "Circulation",
        title: "Circulation Clinical Research and Scientific Statements",
        publisher: "AHA Journals",
        year: "2024",
        url: "https://www.ahajournals.org/journal/circ",
        domain: "cardiology",
        type: "peer-reviewed-journal",
    },
    {
        id: "jco",
        organization: "Journal of Clinical Oncology",
        title: "JCO Oncology Clinical Research",
        publisher: "ASCO Publications",
        year: "2024",
        url: "https://ascopubs.org/journal/jco",
        domain: "oncology",
        type: "peer-reviewed-journal",
    },
];

export const EVIDENCE_ALLOWLIST = PREDICTIVE_REFERENCE_APPENDIX.map((item) => ({
    id: item.id,
    organization: item.organization,
    domain: item.domain,
    type: item.type,
    url: item.url,
}));
