import { generateOpeningScene } from "@/lib/openingSceneEngine";

export const ALL_SCENARIOS = [
  // ── INITIAL ACCESS (3) ──
  {
    title: "The Gatekeeper Filter",
    coreTension: "Rep is trying to establish first real access in a practice that routes everything through staff before the physician sees anyone.",
    description: "A treating clinician's office filters every rep interaction through an MA. The physician has agreed to a brief meeting but is visibly reluctant and preoccupied.",
    stakeholder: "Primary Care Physician",
    objective: "Earn a substantive conversation in a setting designed to prevent one.",
    context: "Primary Care Physician — Busy community practice, high patient volume, routes all rep interactions through staff before the physician sees anyone.",
    openingScene: "I have a few minutes before my next patient. My MA mentioned you had something about prior auth reduction, so I can talk through that briefly.",
    visualScene: generateOpeningScene({ title: "The Gatekeeper Filter", journeyStage: "initial_access", startingBehaviorState: "closed", decisionOrientation: "patient_centric", interactionPressure: ["time_constrained", "operationally_constrained"] }),
    journeyStage: "initial_access", journeyState: "early_discovery",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "time_constrained_community_doctor", startingBehaviorState: "closed",
    interactionPressure: ["time_constrained", "operationally_constrained"],
    predictiveSeed: {
      diseaseState: "primary_care",
      hcpType: "treating_clinician",
      journeyStage: "initial_access",
      interactionPressure: "time_constrained",
      influenceDriver: "patient_centric",
      behaviorArchetype: "time_constrained_community_doctor",
    },
    keyChallenges: ["No trust established yet", "Time pressure used as a shield", "Rep must earn the conversation before delivering any content"],
    suggestedFocusCapabilities: ["question_quality", "customer_engagement_signals", "adaptability"],
    isBuiltIn: true
  },
  {
    title: "The Warm Intro That Turns Cold",
    coreTension: "A colleague referral creates an expectation mismatch — the HCP expected a peer conversation and got a sales visit.",
    description: "An influential physician was referred by a colleague but wasn't told what the conversation was about. The warmth of the referral has already dissipated.",
    stakeholder: "Community Cardiologist",
    objective: "Reset expectations and build enough credibility to have a real conversation.",
    context: "Community Cardiologist — Private cardiology group, recently received a peer referral expecting a case consult, not a product discussion.",
    openingScene: "Dr. Patel said I should talk to you, but honestly, I thought this was going to be a case discussion. I don't usually meet with reps.",
    visualScene: generateOpeningScene({ title: "The Warm Introduction That Turns Cold", journeyStage: "initial_access", startingBehaviorState: "neutral", decisionOrientation: "evidence_driven", interactionPressure: ["skeptical_resistant"] }),
    journeyStage: "initial_access", journeyState: "early_discovery",
    hcpRoleType: "influencer", decisionOrientation: "evidence_driven",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["skeptical_resistant"],
    keyChallenges: ["Expectation mismatch must be acknowledged", "Credibility is earned through questions, not claims", "Rep must not lean on the referral as a shortcut"],
    suggestedFocusCapabilities: ["listening_responsiveness", "question_quality", "conversation_control_structure"],
    isBuiltIn: true
  },
  {
    title: "The No-Show Follow-Up",
    coreTension: "Rep finally gets access after being cancelled or avoided three times.",
    description: "A specialist agreed to a brief meeting after multiple cancellations. The bar to earn engagement is high.",
    stakeholder: "Specialist Physician",
    objective: "Establish enough relevance in the first 90 seconds to earn a real conversation.",
    context: "Specialist Physician — Office-based practice, MA intervenes frequently, has agreed to exactly five minutes between patients after multiple prior cancellations.",
    openingScene: "OK, I have a few minutes. My office manager said you'd been trying to get in. I'll be honest — I'm not usually a fan of these visits, but here we are.",
    visualScene: generateOpeningScene({ title: "The No-Show Follow-Up", journeyStage: "initial_access", startingBehaviorState: "closed", decisionOrientation: "patient_centric", interactionPressure: ["time_constrained", "skeptical_resistant"] }),
    journeyStage: "initial_access", journeyState: "early_discovery",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "time_constrained_community_doctor", startingBehaviorState: "closed",
    interactionPressure: ["time_constrained", "skeptical_resistant"],
    keyChallenges: ["The rep must not default to a pitch", "The opening question is everything", "Relevance must be established before any product content"],
    suggestedFocusCapabilities: ["question_quality", "adaptability", "customer_engagement_signals"],
    isBuiltIn: true
  },
  // ── DISCOVERY (3) ──
  {
    title: "The Undefined Patient Profile",
    coreTension: "Rep can't establish who this HCP actually prescribes for — discovery is wide open.",
    description: "A newer clinician is open to the conversation but hasn't clearly defined their patient criteria.",
    stakeholder: "Hospitalist / Early Career Physician",
    objective: "Use question quality to help the HCP build their own decision criteria.",
    context: "Hospitalist / Early Career Physician — Community hospital, newer attending still building prescribing patterns, genuinely curious and open to guidance.",
    openingScene: "Honestly, I haven't thought much about it. What type of patient are you seeing the best results in?",
    visualScene: generateOpeningScene({ title: "The Undefined Patient Profile", journeyStage: "early_discovery", startingBehaviorState: "open", decisionOrientation: "patient_centric", interactionPressure: ["curious_uncertain"] }),
    journeyStage: "early_discovery", journeyState: "early_discovery",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "curious_uncertain_adopter", startingBehaviorState: "open",
    interactionPressure: ["curious_uncertain"],
    keyChallenges: ["Rep must not fill the vacuum with a pitch", "Discovery must surface real criteria, not assumed ones", "HCP may follow the rep's lead too easily — that's a trap"],
    suggestedFocusCapabilities: ["question_quality", "making_it_matter", "commitment_gaining"],
    isBuiltIn: true
  },
  {
    title: "The Assumed Priority",
    coreTension: "Rep enters discovery with a fixed hypothesis. The HCP has different priorities entirely.",
    description: "A specialist has a well-established practice and clear opinions. The rep's pre-call assumptions don't match the HCP's actual decision criteria.",
    stakeholder: "Endocrinologist",
    objective: "Abandon the assumed agenda and discover what actually matters to this HCP.",
    context: "Endocrinologist — Academic medical center, specialist with strong clinical opinions and a busy referral-based practice, well-read on current data.",
    openingScene: "I've heard the efficacy story. That's not the question for me. The question is what happens to patients who can't stay on therapy.",
    visualScene: generateOpeningScene({ title: "The Assumed Priority", journeyStage: "early_discovery", startingBehaviorState: "neutral", decisionOrientation: "patient_centric", interactionPressure: ["skeptical_resistant"] }),
    journeyStage: "early_discovery", journeyState: "early_discovery",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["skeptical_resistant"],
    keyChallenges: ["Rep's prepared talk track is already irrelevant", "Listening must be demonstrated before any content lands", "The shift to the HCP's real priority must happen fast"],
    suggestedFocusCapabilities: ["listening_responsiveness", "adaptability", "making_it_matter"],
    isBuiltIn: true
  },
  {
    title: "The Protocol Lock",
    coreTension: "HCP is genuinely satisfied with their current protocol. No strong objections, no curiosity.",
    description: "A clinician's current approach works well enough. The rep must discover what, if anything, is genuinely underserved.",
    stakeholder: "Pulmonologist",
    objective: "Surface a real gap in the HCP's current approach without projecting one onto them.",
    context: "Pulmonologist — Community pulmonology practice, stable patient population, limited exposure to newer therapies, comfortable with current protocol.",
    openingScene: "Honestly, my patients do pretty well. I haven't had a reason to change anything in a while. What would make you think I need something different?",
    visualScene: generateOpeningScene({ title: "The Protocol Lock", journeyStage: "early_discovery", startingBehaviorState: "neutral", decisionOrientation: "guideline_anchored", interactionPressure: ["skeptical_resistant"] }),
    journeyStage: "early_discovery", journeyState: "early_discovery",
    hcpRoleType: "treating_clinician", decisionOrientation: "guideline_anchored",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["skeptical_resistant"],
    keyChallenges: ["Comfortable HCPs are harder to move than resistant ones", "Rep must resist the urge to manufacture urgency", "Discovery must find a real patient gap, not a positioning gap"],
    suggestedFocusCapabilities: ["question_quality", "customer_engagement_signals", "making_it_matter"],
    isBuiltIn: true
  },
  // ── CLINICAL VALUE (3) ──
  {
    title: "The Data That Doesn't Land",
    coreTension: "A thought leader has read the trial and disagrees with the rep's framing.",
    description: "A nationally recognized specialist challenges the trial design and questions whether the data applies to their patient population.",
    stakeholder: "Pulmonologist / KOL",
    objective: "Navigate deep clinical skepticism without being defensive or dismissive.",
    context: "Pulmonologist / KOL — Academic center, sits on guideline committees, has read the primary publications and is highly attuned to trial design.",
    openingScene: "The hazard ratio looks good on paper, but the patient population in that trial doesn't reflect what I see. They excluded anyone with moderate renal impairment.",
    visualScene: generateOpeningScene({ title: "The Data That Doesn't Land", journeyStage: "clinical_value", startingBehaviorState: "neutral", decisionOrientation: "evidence_driven", interactionPressure: ["skeptical_resistant"] }),
    journeyStage: "clinical_value", journeyState: "clinical_evaluation",
    hcpRoleType: "thought_leader", decisionOrientation: "evidence_driven",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["skeptical_resistant"],
    predictiveSeed: {
      diseaseState: "pulmonology",
      hcpType: "thought_leader",
      journeyStage: "clinical_value",
      interactionPressure: "skeptical_resistant",
      influenceDriver: "evidence_driven",
      behaviorArchetype: "skeptical_specialist",
    },
    keyChallenges: ["Rep cannot win a clinical debate with a KOL", "Exploring the concern is more credible than defending the data", "Making it matter requires connecting to what the HCP does trust"],
    suggestedFocusCapabilities: ["objection_navigation", "listening_responsiveness", "making_it_matter"],
    isBuiltIn: true
  },
  {
    title: "The Guideline Anchor",
    coreTension: "HCP won't prescribe outside guidelines. The product is appropriate but not yet explicitly guideline-endorsed.",
    description: "A community physician applies guidelines rigidly and will not move until they see explicit guidance from a major society.",
    stakeholder: "Internal Medicine Physician",
    objective: "Help the HCP see where their own patient experience intersects with the available evidence.",
    context: "Internal Medicine Physician — Community practice, conservative prescribing culture, applies guidelines rigidly.",
    openingScene: "I follow the ACC guidelines. Until this shows up there, I'm not changing what I'm doing. What am I missing?",
    visualScene: generateOpeningScene({ title: "The Guideline Anchor", journeyStage: "clinical_value", startingBehaviorState: "closed", decisionOrientation: "guideline_anchored", interactionPressure: ["skeptical_resistant", "competitive_bias"] }),
    journeyStage: "clinical_value", journeyState: "clinical_evaluation",
    hcpRoleType: "treating_clinician", decisionOrientation: "guideline_anchored",
    persona: "skeptical_specialist", startingBehaviorState: "closed",
    interactionPressure: ["skeptical_resistant", "competitive_bias"],
    predictiveSeed: {
      diseaseState: "cardiology",
      hcpType: "treating_clinician",
      journeyStage: "clinical_value",
      interactionPressure: "skeptical_resistant",
      influenceDriver: "guideline_anchored",
      behaviorArchetype: "skeptical_specialist",
    },
    keyChallenges: ["Rep cannot argue against guidelines", "Value must be connected to the HCP's own clinical experience", "Discovery about real patient gaps is the only productive path"],
    suggestedFocusCapabilities: ["question_quality", "making_it_matter", "adaptability"],
    isBuiltIn: true
  },
  {
    title: "The Cost-Effectiveness Filter",
    coreTension: "HCP accepts the clinical data but runs every prescription decision through a cost-effectiveness lens.",
    description: "A value-driven clinician is not questioning efficacy — they're asking whether the outcome justifies the cost.",
    stakeholder: "Internal Medicine / Hospital Medicine Physician",
    objective: "Shift from clinical value to economic and patient-outcome value framing.",
    context: "Internal Medicine / Hospital Medicine Physician — Large health system with formulary cost pressures, sits on a P&T advisory group.",
    openingScene: "The efficacy data is fine. For the patients who would actually use this, does the outcome justify what we'd spend? How do you justify the cost?",
    visualScene: generateOpeningScene({ title: "The Cost-Effectiveness Filter", journeyStage: "clinical_value", startingBehaviorState: "neutral", decisionOrientation: "evidence_driven", interactionPressure: ["operationally_constrained", "access_barrier"] }),
    journeyStage: "clinical_value", journeyState: "clinical_evaluation",
    hcpRoleType: "influencer", decisionOrientation: "evidence_driven",
    persona: "cost_focused_decision_maker", startingBehaviorState: "neutral",
    interactionPressure: ["operationally_constrained", "access_barrier"],
    keyChallenges: ["Efficacy data is not the ask", "Rep must connect specific patient profiles to value, not population averages", "Generic health economics will not land"],
    suggestedFocusCapabilities: ["making_it_matter", "question_quality", "adaptability"],
    isBuiltIn: true
  },
  // ── OBJECTION HANDLING (3) ──
  {
    title: "The Prior Auth Reflex",
    coreTension: "Every access concern becomes a prior auth conversation before the clinical value has been established.",
    description: "A treating clinician raises prior auth at the start as a reason not to engage.",
    stakeholder: "Rheumatologist",
    objective: "Separate the access question from the clinical decision and hold both in the conversation.",
    context: "Rheumatologist — Private practice, staff already burned out by prior auth volume, operational constraints drive most clinical decisions.",
    openingScene: "Before you say anything — if there's a prior auth requirement, this conversation is over. We don't have the bandwidth.",
    visualScene: generateOpeningScene({ title: "The Prior Auth Reflex", journeyStage: "objection_handling", startingBehaviorState: "closed", decisionOrientation: "patient_centric", interactionPressure: ["operationally_constrained", "access_barrier"] }),
    journeyStage: "objection_handling", journeyState: "objection_phase",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "time_constrained_community_doctor", startingBehaviorState: "closed",
    interactionPressure: ["operationally_constrained", "access_barrier"],
    keyChallenges: ["Access objection is a reflex, not a considered concern", "Rep must acknowledge without collapsing the conversation", "Clinical discovery still needs to happen"],
    suggestedFocusCapabilities: ["objection_navigation", "conversation_control_structure", "listening_responsiveness"],
    isBuiltIn: true
  },
  {
    title: "The Unexpected Safety Flag",
    coreTension: "HCP raises a safety concern the rep wasn't expecting.",
    description: "A specialist brings up a case they heard about at a conference — an adverse event the rep hasn't encountered in their training.",
    stakeholder: "Neurologist",
    objective: "Acknowledge the concern genuinely, explore it fully, and respond without defensiveness.",
    context: "Neurologist — Academic neurology practice, recently attended a major conference where an adverse event was presented.",
    openingScene: "I was at AAN last month and someone presented a case — hepatic signal, possibly related to your product. Has your medical team seen this?",
    visualScene: generateOpeningScene({ title: "The Unexpected Safety Flag", journeyStage: "objection_handling", startingBehaviorState: "neutral", decisionOrientation: "risk_averse", interactionPressure: ["safety_concern"] }),
    journeyStage: "objection_handling", journeyState: "objection_phase",
    hcpRoleType: "treating_clinician", decisionOrientation: "risk_averse",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["safety_concern"],
    keyChallenges: ["Rep cannot dismiss or minimize the concern", "Acknowledging uncertainty builds more trust than defending the product", "The rep may need to escalate to medical"],
    suggestedFocusCapabilities: ["objection_navigation", "listening_responsiveness", "adaptability"],
    isBuiltIn: true
  },
  {
    title: "The Competitive Defender",
    coreTension: "HCP has a loyal relationship with a competitor product and filters every conversation through that lens.",
    description: "A specialist has been using a competitor therapy for years.",
    stakeholder: "Oncologist",
    objective: "Explore what the HCP values in their current choice without attacking it.",
    context: "Oncologist — Community oncology practice, has maintained a long-standing relationship with a competitor therapy.",
    openingScene: "I've been using [Competitor] for three years. My patients do well on it. Unless you can show me something that matters to them specifically, I'm not interested in switching.",
    visualScene: generateOpeningScene({ title: "The Competitive Defender", journeyStage: "objection_handling", startingBehaviorState: "closed", decisionOrientation: "patient_centric", interactionPressure: ["competitive_bias", "skeptical_resistant"] }),
    journeyStage: "objection_handling", journeyState: "objection_phase",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "skeptical_specialist", startingBehaviorState: "closed",
    interactionPressure: ["competitive_bias", "skeptical_resistant"],
    keyChallenges: ["Attacking the competitor damages credibility", "Rep must explore the HCP's values before presenting any differentiation", "The opening move must be a question, not a claim"],
    suggestedFocusCapabilities: ["question_quality", "listening_responsiveness", "making_it_matter"],
    isBuiltIn: true
  },
  // ── ADOPTION & IMPLEMENTATION (3) ──
  {
    title: "The Reluctant Early Adopter",
    coreTension: "HCP is genuinely interested but won't act until someone else does first.",
    description: "A clinician acknowledges the clinical case but is waiting for peer adoption before prescribing.",
    stakeholder: "Nephrologist",
    objective: "Distinguish clinical readiness from decision readiness and move toward a specific next step.",
    context: "Nephrologist — Academic nephrology, respects the clinical data but cautious about early adoption.",
    openingScene: "I think the data is compelling. I'm just not ready to be the first one in my group to change protocols. What are others in my area doing?",
    visualScene: generateOpeningScene({ title: "The Reluctant Early Adopter", journeyStage: "adoption_implementation", startingBehaviorState: "neutral", decisionOrientation: "risk_averse", interactionPressure: ["curious_uncertain"] }),
    journeyStage: "adoption_implementation", journeyState: "adoption_commitment",
    hcpRoleType: "treating_clinician", decisionOrientation: "risk_averse",
    persona: "curious_uncertain_adopter", startingBehaviorState: "neutral",
    interactionPressure: ["curious_uncertain"],
    keyChallenges: ["Clinical readiness does not equal decision readiness", "Rep must identify the actual barrier", "The ask must be sized to the HCP's current comfort level"],
    suggestedFocusCapabilities: ["customer_engagement_signals", "commitment_gaining", "question_quality"],
    isBuiltIn: true
  },
  {
    title: "The Workflow Bottleneck",
    coreTension: "The product fits clinically but the practice workflow doesn't support it.",
    description: "A clinician is supportive of the therapy but the practice's workflow creates a real barrier.",
    stakeholder: "Dermatologist",
    objective: "Explore the workflow barrier specifically and help the HCP identify what would need to change.",
    context: "Dermatologist — Solo or small group practice, limited staff, no prior experience with the administration or monitoring requirements.",
    openingScene: "Clinically, I'm on board. But we'd need someone to manage the monitoring. I don't have the staff infrastructure that a bigger practice would have.",
    visualScene: generateOpeningScene({ title: "The Workflow Bottleneck", journeyStage: "adoption_implementation", startingBehaviorState: "neutral", decisionOrientation: "patient_centric", interactionPressure: ["operationally_constrained"] }),
    journeyStage: "adoption_implementation", journeyState: "adoption_commitment",
    hcpRoleType: "treating_clinician", decisionOrientation: "patient_centric",
    persona: "time_constrained_community_doctor", startingBehaviorState: "neutral",
    interactionPressure: ["operationally_constrained"],
    keyChallenges: ["Workflow objection is real, not reflexive", "Rep must explore specifics before offering solutions", "Generic reassurance about support services will not land"],
    suggestedFocusCapabilities: ["question_quality", "making_it_matter", "adaptability"],
    isBuiltIn: true
  },
  {
    title: "The Reversal After First Patient",
    coreTension: "HCP tried the therapy with one patient, something went wrong, and they are now recalibrating.",
    description: "A clinician who was an early adopter experienced a difficult first case and has paused all new starts.",
    stakeholder: "Hematologist",
    objective: "Understand what happened, separate the case from the product, and re-establish clinical confidence.",
    context: "Hematologist — Academic hematology, was an enthusiastic early adopter, first patient had a complication, has paused all new starts.",
    openingScene: "I tried it with one patient and had a rough experience. I'm not ready to start anyone else until I understand what happened. Can you help me think through this?",
    visualScene: generateOpeningScene({ title: "The Reversal After First Patient", journeyStage: "adoption_implementation", startingBehaviorState: "neutral", decisionOrientation: "risk_averse", interactionPressure: ["safety_concern", "skeptical_resistant"] }),
    journeyStage: "adoption_implementation", journeyState: "adoption_commitment",
    hcpRoleType: "treating_clinician", decisionOrientation: "risk_averse",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["safety_concern", "skeptical_resistant"],
    keyChallenges: ["Rep must explore before explaining", "One case should not define the therapy — but the HCP's concern is real", "Medical escalation may be appropriate"],
    suggestedFocusCapabilities: ["listening_responsiveness", "objection_navigation", "making_it_matter"],
    isBuiltIn: true
  },
  // ── ACCESS & FORMULARY (1) ──
  {
    title: "The Formulary Firewall",
    coreTension: "The product has clinical support from the prescriber but is blocked at the formulary level.",
    description: "A clinician who wants to prescribe runs into a hard formulary exclusion.",
    stakeholder: "Specialist Physician + P&T Committee Influencer",
    objective: "Clarify the actual formulary pathway and agree on a specific advocacy next step.",
    context: "Specialist Physician / P&T Committee Influencer — Large integrated health system, product is non-preferred on formulary.",
    openingScene: "I'd actually like to use this, but our formulary team flagged it as non-preferred. I don't know what I can do about that — is there even a process?",
    visualScene: generateOpeningScene({ title: "The Formulary Firewall", journeyStage: "access_formulary", startingBehaviorState: "neutral", decisionOrientation: "patient_centric", interactionPressure: ["access_barrier", "operationally_constrained"] }),
    journeyStage: "access_formulary", journeyState: "access_formulary",
    hcpRoleType: "influencer", decisionOrientation: "patient_centric",
    persona: "curious_uncertain_adopter", startingBehaviorState: "neutral",
    interactionPressure: ["access_barrier", "operationally_constrained"],
    keyChallenges: ["Rep must be accurate about the pathway — overpromising destroys trust", "HCP's advocacy role must be surfaced and sized correctly", "The next step must be actionable by this specific HCP"],
    suggestedFocusCapabilities: ["commitment_gaining", "conversation_control_structure", "making_it_matter"],
    isBuiltIn: true
  },
  // ── COMMITMENT & CLOSE (3) ──
  {
    title: "The Perpetual Maybe",
    coreTension: "HCP agrees in principle but never commits to a specific next step.",
    description: "A clinician consistently says the right things but has been in the same place for three visits.",
    stakeholder: "Gastroenterologist",
    objective: "Distinguish genuine alignment from passive agreement and ask for a proportionate next step.",
    context: "Gastroenterologist — Private GI practice, has had positive conversations across three prior visits but has not started any trial patients.",
    openingScene: "Yes, I've been meaning to try it with the right patient. I just haven't had one come through that fits perfectly yet.",
    visualScene: generateOpeningScene({ title: "The Perpetual Maybe", journeyStage: "commitment_close", startingBehaviorState: "neutral", decisionOrientation: "risk_averse", interactionPressure: ["curious_uncertain"] }),
    journeyStage: "commitment_close", journeyState: "adoption_commitment",
    hcpRoleType: "treating_clinician", decisionOrientation: "risk_averse",
    persona: "curious_uncertain_adopter", startingBehaviorState: "neutral",
    interactionPressure: ["curious_uncertain"],
    keyChallenges: ["Conceptual agreement is not commitment", "Rep must define what the 'right patient' looks like with the HCP", "The ask must be specific, time-bound, and easy to say yes to"],
    suggestedFocusCapabilities: ["commitment_gaining", "question_quality", "conversation_control_structure"],
    isBuiltIn: true
  },
  {
    title: "The Handoff Risk",
    coreTension: "HCP is ready to move but believes the final decision belongs to someone else.",
    description: "A senior clinician who influenced the decision process now defers the actual commitment to a committee.",
    stakeholder: "Senior Physician / Department Head",
    objective: "Secure a concrete commitment before the conversation ends.",
    context: "Senior Physician / Department Head — Academic or group practice, has been the internal champion throughout the process.",
    openingScene: "I'm supportive, you know that. But this is ultimately a formulary decision. I'll bring it up at the next P&T meeting — that's probably in six weeks.",
    visualScene: generateOpeningScene({ title: "The Handoff Risk", journeyStage: "commitment_close", startingBehaviorState: "open", decisionOrientation: "patient_centric", interactionPressure: ["access_barrier"] }),
    journeyStage: "commitment_close", journeyState: "adoption_commitment",
    hcpRoleType: "influencer", decisionOrientation: "patient_centric",
    persona: "curious_uncertain_adopter", startingBehaviorState: "open",
    interactionPressure: ["access_barrier"],
    keyChallenges: ["Deference to a committee is sometimes avoidance", "Rep must clarify what this HCP can own right now", "Next step must be mutual and specific"],
    suggestedFocusCapabilities: ["commitment_gaining", "conversation_control_structure", "customer_engagement_signals"],
    isBuiltIn: true
  },
  {
    title: "The Split Decision",
    coreTension: "Two partners in the same practice have opposite views and the rep is in the room with both of them.",
    description: "A joint meeting surfaces a real disagreement between two physicians.",
    stakeholder: "Two-Physician Practice Group",
    objective: "Hold the dynamic, explore both positions, and find a next step both physicians can own.",
    context: "Two-Physician Practice Group — Small specialty group, partners share patient load and make formulary decisions jointly.",
    openingScene: "Actually, Dr. Chen wanted to sit in on this one. We've been going back and forth on whether to add this to our toolkit. Maybe you can help us sort it out.",
    visualScene: generateOpeningScene({ title: "The Split Decision", journeyStage: "commitment_close", startingBehaviorState: "neutral", decisionOrientation: "evidence_driven", interactionPressure: ["skeptical_resistant", "competitive_bias"] }),
    journeyStage: "commitment_close", journeyState: "adoption_commitment",
    hcpRoleType: "influencer", decisionOrientation: "evidence_driven",
    persona: "skeptical_specialist", startingBehaviorState: "neutral",
    interactionPressure: ["skeptical_resistant", "competitive_bias"],
    keyChallenges: ["Rep cannot favor one physician over the other", "Each physician's concern must be individually surfaced", "Commitment must come from alignment, not pressure"],
    suggestedFocusCapabilities: ["conversation_control_structure", "listening_responsiveness", "commitment_gaining"],
    isBuiltIn: true
  }
];

const GRID_FILTER_MAP_BY_TITLE = {
  "The Gatekeeper Filter": { diseaseState: "primary_care", specialty: "primary_care", interactionPressure: "time_constrained" },
  "The Warm Intro That Turns Cold": { diseaseState: "cardiology", specialty: "specialist", interactionPressure: "skeptical_resistant" },
  "The No-Show Follow-Up": { diseaseState: "primary_care", specialty: "specialist", interactionPressure: "time_constrained" },
  "The Undefined Patient Profile": { diseaseState: "primary_care", specialty: "hospital_medicine", interactionPressure: "curious_uncertain" },
  "The Assumed Priority": { diseaseState: "endocrinology", specialty: "academic", interactionPressure: "skeptical_resistant" },
  "The Protocol Lock": { diseaseState: "pulmonology", specialty: "specialist", interactionPressure: "skeptical_resistant" },
  "The Data That Doesn't Land": { diseaseState: "pulmonology", specialty: "academic", interactionPressure: "skeptical_resistant" },
  "The Guideline Anchor": { diseaseState: "cardiology", specialty: "primary_care", interactionPressure: "skeptical_resistant" },
  "The Cost-Effectiveness Filter": { diseaseState: "primary_care", specialty: "hospital_medicine", interactionPressure: "operationally_constrained" },
  "The Prior Auth Reflex": { diseaseState: "rheumatology", specialty: "specialist", interactionPressure: "access_barrier" },
  "The Unexpected Safety Flag": { diseaseState: "neurology", specialty: "academic", interactionPressure: "safety_concern" },
  "The Competitive Defender": { diseaseState: "oncology", specialty: "specialist", interactionPressure: "competitive_bias" },
  "The Reluctant Early Adopter": { diseaseState: "nephrology", specialty: "academic", interactionPressure: "curious_uncertain" },
  "The Workflow Bottleneck": { diseaseState: "dermatology", specialty: "specialist", interactionPressure: "operationally_constrained" },
  "The Reversal After First Patient": { diseaseState: "hematology", specialty: "academic", interactionPressure: "safety_concern" },
  "The Formulary Firewall": { diseaseState: "primary_care", specialty: "academic", interactionPressure: "access_barrier" },
  "The Perpetual Maybe": { diseaseState: "gastroenterology", specialty: "specialist", interactionPressure: "curious_uncertain" },
  "The Handoff Risk": { diseaseState: "primary_care", specialty: "academic", interactionPressure: "access_barrier" },
  "The Split Decision": { diseaseState: "primary_care", specialty: "specialist", interactionPressure: "skeptical_resistant" },
};

for (const scenario of ALL_SCENARIOS) {
  const mapped = GRID_FILTER_MAP_BY_TITLE[scenario.title] || {};
  scenario.gridMapping = {
    diseaseState: mapped.diseaseState || scenario.predictiveSeed?.diseaseState || "",
    specialty: mapped.specialty || "",
    hcpType: scenario.hcpRoleType || "",
    influenceDriver: scenario.decisionOrientation || "",
    journeyStage: scenario.journeyStage || "",
    interactionPressure: mapped.interactionPressure || scenario.interactionPressure?.[0] || "",
  };
}
