// smoke-realism-lever-transcript.test.ts
// Test: realism lever effect on HCP tone, coaching, and adaptation
import { ALL_SCENARIOS } from "../src/lib/scenarioCatalog.js";
import { buildScenarioContract, evaluateRepResponse } from "../worker/rps/engine.js";

const realismLevels = [2, 6, 9]; // low, medium, high realism
const scenario = ALL_SCENARIOS.find(s => s.title && typeof s.title === 'string'); // Pick first scenario for consistency

function simulateTranscript(realismLevel) {
  let contract = buildScenarioContract({ ...scenario, realismLevel });
  let memory = { resistance_trend: "stable", trust_trend: "neutral" };
  let lastRep = "";
  let lastHcp = scenario.openingScene;
  const transcript = [];
  for (let turn = 1; turn <= 6; ++turn) {
    // Rep attempts to adapt: echoes HCP, then tries a cue-aligned question
    lastRep = turn === 1
      ? `Thanks for sharing. What would make this visit most valuable for you?`
      : `I hear: "${lastHcp}". What matters most about that for your practice?`;
    // Evaluate rep response and get updated memory
    const evalResult = evaluateRepResponse({
      repResponseTranscript: lastRep,
      cueSignal: contract.cue_signal,
      repSelectedTemperature: realismLevel,
      scenarioContext: contract,
      conversationMemory: memory,
    });
    memory = evalResult.conversation_memory;
    // Use the actual HCP engine to generate the next HCP line (AI coach as HCP)
    contract = buildScenarioContract({ ...scenario, realismLevel }); // ensure contract is fresh per turn if needed
    const hcpEval = buildScenarioContract({ ...scenario, realismLevel });
    // The HCP's next line is generated by the engine, using the adaptive/predictive layers
    const hcpLine = contract.hcp_statement_or_question || "(no HCP line generated)";
    lastHcp = hcpLine;
    transcript.push({
      turn,
      rep: lastRep,
      hcp: lastHcp,
      score: evalResult.overall_score,
      resistance: memory.resistance_trend,
      coaching: evalResult.coaching_feedback || [],
    });
  }
  return transcript;
}

const results = realismLevels.map(level => ({
  realismLevel: level,
  transcript: simulateTranscript(level),
}));

results.forEach(({ realismLevel, transcript }) => {
  console.log(`\n=== Transcript for Realism Level ${realismLevel} ===`);
  transcript.forEach(({ turn, rep, hcp, score, resistance, coaching }) => {
    console.log(`Turn ${turn}:`);
    console.log(`  Rep: ${rep}`);
    console.log(`  HCP: ${hcp}`);
    console.log(`  [Score: ${score}, Resistance: ${resistance}]`);
    if (coaching.length) {
      console.log(`  Coaching: ${coaching.join(" | ")}`);
    }
  });
});
